package de.useweb.backend.domain.validation;

public enum ValidationErrorCode {
    SYNTAX_ERROR,
    TYPE_ERROR,
    UNKNOWN_CLASS,
    UNKNOWN_ATTRIBUTE,
    INVALID_SLOT_VALUE,
    INVALID_LINK,
    ASSOCIATION_CLASS_IDENTITY_VIOLATION,
    COMPOSITE_OWNERSHIP_VIOLATION,
    COMPOSITION_CYCLE,
    MULTIPLICITY_VIOLATION,
    INVARIANT_VIOLATION,
    EVALUATION_ERROR
}
